variable "block_ref" {
  type        = string
  description = "Short app reference used as the base for resource names."
}

variable "resource_suffix" {
  type        = string
  description = "Random suffix appended to resource names for uniqueness. Generated by the caller (typically a 5-char random_string)."
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Tags applied to all AWS resources managed by the scaffold."
}

variable "bucket_arn" {
  type        = string
  description = "ARN of the S3 bucket the deployer is allowed to write to. The caller owns the bucket; this module only grants the deployer role access to it."
}

variable "cdn_arns" {
  type        = list(string)
  default     = []
  description = "ARNs of CloudFront distributions in front of the bucket. When non-empty, the deployer role is granted GetDistribution/UpdateDistribution/CreateInvalidation/GetInvalidation on these distributions so post-deploy cache invalidations work."
}

variable "op_assumer_arns" {
  type        = list(string)
  description = "ARNs of principals allowed to sts:AssumeRole the deployer role. Typically `[ns_agent_user_arn]`."
}

variable "log_retention_in_days" {
  type        = number
  default     = 365
  description = "CloudWatch log group retention. Forwarded to the wrapped logs module."
}
